In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [1]:
2+3


[1] 5

In [6]:
6/3


[1] 2

In [7]:
(3*8)/(2+3)

[1] 4.8

In [8]:
log(12)

[1] 2.484907

In [10]:
x<-1:10
cat(x)
cat('mean of x is',mean(x),'\n')
cat('median of x is',median(x),'\n')
cat('variance of x is',var(x),'\n')
cat('standard deviation of x is',sd(x),'\n')

1 2 3 4 5 6 7 8 9 10mean of x is 5.5 
median of x is 5.5 
variance of x is 9.166667 
standard deviation of x is 3.02765 


In [11]:
x<-1:10
cat(x)
cat('mean of x is',mean(x))
cat('median of x is',median(x))
cat('variance of x is',var(x))
cat('standard deviation of x is',sd(x))

1 2 3 4 5 6 7 8 9 10mean of x is 5.5median of x is 5.5variance of x is 9.166667standard deviation of x is 3.02765

In [12]:
x<-1:10
print(x)
print(paste('mean of x is',mean(x)))
print(paste('median of x is',median(x)))
print(paste('variance of x is',var(x)))
print(paste('standrad deviation of x is',sd(x)))

 [1]  1  2  3  4  5  6  7  8  9 10
[1] "mean of x is 5.5"
[1] "median of x is 5.5"
[1] "variance of x is 9.16666666666667"
[1] "standrad deviation of x is 3.02765035409749"


In [14]:
x<-"dataset"
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] "dataset"

[1] "character"

[1] "character"

[1] 1

NULL

In [16]:
x<-2
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 2

[1] "numeric"

[1] "double"

[1] 1

NULL

In [17]:
x<-56L
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 56

[1] "integer"

[1] "integer"

[1] 1

NULL

In [18]:
x<-2+3i
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 2+3i

[1] "complex"

[1] "complex"

[1] 1

NULL

In [19]:
x<-TRUE
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] TRUE

[1] "logical"

[1] "logical"

[1] 1

NULL

In [20]:
vector()# an empty 'logical' (the default) vector

logical(0)

In [21]:
vector("character",length=5)

[1] "" "" "" "" ""

In [22]:
character(5)

[1] "" "" "" "" ""

In [23]:
numeric(5)

[1] 0 0 0 0 0

In [24]:
logical(5)

[1] FALSE FALSE FALSE FALSE FALSE

In [26]:
#numeric vector having 5 elements
x<-c(12,23,34,45,56)

In [27]:
x
class(x)

[1] 12 23 34 45 56

[1] "numeric"

In [28]:
y<-c(TRUE,TRUE,FALSE,FALSE,TRUE)
y
class(y)
length(y)




[1]  TRUE  TRUE FALSE FALSE  TRUE

[1] "logical"

[1] 5

In [29]:
z<-c("nav","tej","sum")
z
class(z)
length(z)

[1] "nav" "tej" "sum"

[1] "character"

[1] 3

In [30]:
print("elements in z before")
z
z<-c(z,"annette")
print("elements in z after adding new element")
z

[1] "elements in z before"


[1] "nav" "tej" "sum"

[1] "elements in z after adding new element"


[1] "nav"     "tej"     "sum"     "annette"

In [31]:
print("elements in z before")
z
z<-c("annette",z)
print("elements in z after adding new element")
z

[1] "elements in z before"


[1] "nav"     "tej"     "sum"     "annette"

[1] "elements in z after adding new element"


[1] "annette" "nav"     "tej"     "sum"     "annette"

In [32]:
a<-1:10
a

[1]  1  2  3  4  5  6  7  8  9 10

In [33]:
seq(10)

[1]  1  2  3  4  5  6  7  8  9 10

In [34]:
seq(from=1,to=10,by=0.1)

[1]  1.0  1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.0  2.1  2.2  2.3  2.4
[16]  2.5  2.6  2.7  2.8  2.9  3.0  3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9
[31]  4.0  4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.0  5.1  5.2  5.3  5.4
[46]  5.5  5.6  5.7  5.8  5.9  6.0  6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
[61]  7.0  7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.0  8.1  8.2  8.3  8.4
[76]  8.5  8.6  8.7  8.8  8.9  9.0  9.1  9.2  9.3  9.4  9.5  9.6  9.7  9.8  9.9
[91] 10.0

In [35]:
1/10

[1] 0.1

In [36]:
0/0

[1] NaN

In [38]:
exp(-Inf)

[1] 0

In [39]:
log(0)

[1] -Inf

In [40]:
log(1)

[1] 0

In [43]:
a<-c(1.7,"a")
a

[1] "1.7" "a"

In [46]:
b<-c(TRUE,2,3,FALSE)
b

[1] 1 2 3 0

In [47]:
c<-c("a",TRUE)
c

[1] "a"    "TRUE"

In [48]:
as.numeric("1")

[1] 1

In [49]:
as.numeric(c("45","66"))

[1] 45 66

In [50]:
as.numeric(c("45","66","six"))

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

[1] 45 66 NA

In [51]:
as.character(22)

[1] "22"

In [52]:
as.character(c(22,35,56))

[1] "22" "35" "56"

In [54]:
m<-matrix(nrow=2,ncol=2)
m

[,1] [,2]
[1,] NA   NA  
[2,] NA   NA

In [55]:
dim(m)


[1] 2 2

In [56]:
class(m)


[1] "matrix"

In [57]:
typeof(m)

[1] "logical"

In [58]:
m<-matrix(c(1:3))
print('given matrix is')
print(m)
print('dimensions (size) of given matrix is')
print(dim(m))
print('class of given matrix is')
print(class(m))
print('type of given matrix is')
print(typeof(m))

[1] "given matrix is"
     [,1]
[1,]    1
[2,]    2
[3,]    3
[1] "dimensions (size) of given matrix is"
[1] 3 1
[1] "class of given matrix is"
[1] "matrix"
[1] "type of given matrix is"
[1] "integer"


In [59]:
a<-matrix(1:6,nrow=2,ncol=3)
print(a)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [61]:
m<-1:10
print(m)
print(dim(m))
dim(m)<-c(2,5)
print(m)
print(dim(m))

 [1]  1  2  3  4  5  6  7  8  9 10
NULL
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
[1] 2 5


In [62]:
my_name<-readline(prompt="enter name:")
my_age<-readline(prompt="enter age:")
my_age<-as.integer(my_age)
print(paste("H1,",my_name,"next year you will be",my_age+1,"years old."))

enter name:naveen
enter age:18
[1] "H1, naveen next year you will be 19 years old."


In [63]:
w<-readline()
w

helloooooooo


[1] "helloooooooo"

#data types in R

In [64]:
g=62.4
g

[1] 62.4

In [65]:
s=as.integer(30)
s


[1] 30

In [66]:
as.integer(3.14)

[1] 3

In [67]:
k=1+2i
k

[1] 1+2i

In [68]:
sqrt(-1)

Warning message in sqrt(-1):
“NaNs produced”

[1] NaN

In [69]:
a=4;b=6
g=a>b
g

[1] FALSE

In [70]:
g=as.character(32.48)
g

[1] "32.48"

In [71]:
class(g)

[1] "character"